baseURL = 'https://germanrodriguez98.github.io/hardware3/'
languageCode = 'es-ar'
title = 'Mi Página Hugo'
theme = 'ananke'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
